name: gmail_statement_reader
description: A Flutter app to read Gmail statement emails with PDF attachments.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  enough_mail: ^2.1.6
  intl: ^0.19.0
  path_provider: ^2.1.2
  open_file: ^3.3.2
  permission_handler: ^11.3.0
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.2.4
  syncfusion_flutter_pdf: ^24.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
